# Generated by Django 2.2.10 on 2020-06-11 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='commentId',
        ),
    ]
