# Generated by Django 2.2.5 on 2020-06-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200627_1922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='thumbnail',
            new_name='Image',
        ),
    ]
