# Generated by Django 2.2.5 on 2020-06-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200627_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
