# Generated by Django 2.2.5 on 2020-06-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
