# Generated by Django 2.2.5 on 2020-06-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='newmessage',
            field=models.CharField(max_length=500),
        ),
    ]
