# Generated by Django 2.2.10 on 2020-06-10 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
